# Generated by Django 5.1 on 2024-08-12 17:04

import django.db.models.deletion
import platformTK.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numéro_de_téléphone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('slugEtudiant', models.CharField(blank=True, default=platformTK.models.generate_etudiant_code, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
