# Generated by Django 5.1 on 2024-08-12 19:33

import django.db.models.deletion
import platformTK.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='EtudiantCode',
            field=models.CharField(blank=True, default=platformTK.models.generate_etudiant_code, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='slugEtudiant',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numéro_de_téléphone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('slugProf', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ProfCode', models.CharField(blank=True, default=platformTK.models.generate_prof_code, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
