# Generated by Django 5.1 on 2024-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='yuhdujqshjdhjhdjzezoehzfedbcb zjkc zijbeijzi', max_length=300),
            preserve_default=False,
        ),
    ]
