# Generated by Django 5.1 on 2024-08-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0004_group_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
