# Generated by Django 5.1 on 2024-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0005_rename_group_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
