# Generated by Django 5.1 on 2024-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0006_etudiant_points_alter_etudiant_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
