# Generated by Django 5.1 on 2024-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0008_competitions_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
