# Generated by Django 5.1 on 2024-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0011_competitions_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
