# Generated by Django 5.1 on 2024-08-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0012_competitions_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='prof',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='platformTK.prof'),
            preserve_default=False,
        ),
    ]
