# Generated by Django 5.1 on 2024-08-28 15:13

import platformTK.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductCode',
            field=models.CharField(blank=True, default=platformTK.models.generate_product_code, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
