# Generated by Django 5.1 on 2024-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('livre', 'livre'), ('jeux', 'jeux'), ('stylos', 'stylos'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
