# Generated by Django 5.1 on 2024-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0024_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='platformTK.groups'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='platformTK.prof'),
        ),
    ]
