# Generated by Django 5.1 on 2024-09-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformTK.etudiant'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformTK.product'),
        ),
    ]
