# Generated by Django 5.1 on 2024-09-09 16:24

import django.db.models.deletion
import platformTK.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0028_alter_commande_etudiant_alter_commande_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='EtudiantCode',
            field=models.CharField(blank=True, default=platformTK.models.generate_etudiant_code, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformTK.etudiant'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformTK.groups'),
        ),
    ]
