# Generated by Django 5.1 on 2024-09-09 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0031_alter_prof_profcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
