# Generated by Django 5.1 on 2024-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0032_category_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
