# Generated by Django 5.1 on 2024-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0033_alter_etudiant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
