# Generated by Django 5.1 on 2024-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0034_alter_etudiant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/786530_people_512x512.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
