# Generated by Django 5.1 on 2024-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0041_alter_attendance_is_present_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
