# Generated by Django 5.1 on 2024-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0043_alter_class_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
