# Generated by Django 5.1 on 2024-09-24 13:05

import django.db.models.deletion
import platformTK.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0045_alter_class_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(default=platformTK.models.generate_class_code, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='class',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='platformTK.prof'),
        ),
    ]
