# Generated by Django 5.1 on 2024-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0046_class_class_code_class_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
