# Generated by Django 5.1 on 2024-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0050_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
