# Generated by Django 5.1 on 2024-10-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0053_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
