# Generated by Django 5.1 on 2024-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0054_alter_parents_avatar_alter_parents_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='parents', to='platformTK.etudiant'),
        ),
    ]
