# Generated by Django 5.1 on 2024-10-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0057_usercompetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validated', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platformTK.attendance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_validations', to='platformTK.prof')),
            ],
        ),
    ]
