# Generated by Django 5.1 on 2024-10-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0058_absencevalidation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbsenceValidation',
        ),
    ]
