# Generated by Django 5.1 on 2024-10-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0059_delete_absencevalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformTK.class')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformTK.prof')),
            ],
        ),
    ]
