# Generated by Django 5.1 on 2024-10-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0060_attendancevalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceValidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('absence_status', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformTK.groups')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformTK.prof')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceValidation',
        ),
    ]
