# Generated by Django 5.1 on 2024-10-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0062_absencevalidationhistory_is_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencevalidationhistory',
            name='is_attendance',
        ),
        migrations.AddField(
            model_name='absencevalidationhistory',
            name='class_instance',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='platformTK.class'),
            preserve_default=False,
        ),
    ]
