# Generated by Django 5.1 on 2024-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0063_remove_absencevalidationhistory_is_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencevalidationhistory',
            name='absence_status',
            field=models.CharField(max_length=20),
        ),
    ]
