# Generated by Django 5.1 on 2024-10-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0064_alter_absencevalidationhistory_absence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencevalidationhistory',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platformTK.prof'),
        ),
    ]
