# Generated by Django 5.1 on 2024-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0065_alter_absencevalidationhistory_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
