# Generated by Django 5.1 on 2024-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0066_alter_prof_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='language',
            field=models.CharField(choices=[('Anglais', 'Anglais'), ('Français', 'Français')], default='Français', max_length=50),
            preserve_default=False,
        ),
    ]
