# Generated by Django 5.1 on 2024-11-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0068_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='platformTK.center'),
            preserve_default=False,
        ),
    ]
