# Generated by Django 5.1 on 2024-11-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0069_groups_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='platformTK.center'),
        ),
    ]
