# Generated by Django 5.1 on 2024-11-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformTK', '0070_alter_groups_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='center',
        ),
        migrations.DeleteModel(
            name='Center',
        ),
    ]
